/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaFrame;

/**
 *
 * @author pc
 */
public class FrameBT8_C0 extends javax.swing.JFrame {

    /**
     * Creates new form FrameBT8_C0
     */
    public FrameBT8_C0() {
        initComponents();
    }
    
    public static final int Max = 1000;
    String X[] = new String[Max];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogThemMoi = new javax.swing.JDialog();
        btnOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtViTriCT = new javax.swing.JTextField();
        txtGiaTriCT = new javax.swing.JTextField();
        dialogXoa = new javax.swing.JDialog();
        btnOK1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtViTriCX = new javax.swing.JTextField();
        dialogKTx = new javax.swing.JDialog();
        btnOK2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPTCT = new javax.swing.JTextField();
        thoatButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BkLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        soTNTextField = new javax.swing.JTextField();
        chooseComboBox = new javax.swing.JComboBox<>();
        btnThucHien = new javax.swing.JButton();
        xoaButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nhapmangTextArea = new javax.swing.JTextArea();

        dialogThemMoi.setTitle("Thêm mới một phần tử vào mảng");
        dialogThemMoi.setMinimumSize(new java.awt.Dimension(400, 300));

        btnOK.setText("OK");
        btnOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel4.setText("THÊM MỘT PHẦN TỬ MỚI VÀO MẢNG");

        jLabel5.setText("Vị trí của phần tử cần thêm: ");

        jLabel6.setText("Giá trị của phần tử cẩn thêm: ");

        txtViTriCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViTriCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogThemMoiLayout = new javax.swing.GroupLayout(dialogThemMoi.getContentPane());
        dialogThemMoi.getContentPane().setLayout(dialogThemMoiLayout);
        dialogThemMoiLayout.setHorizontalGroup(
            dialogThemMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogThemMoiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(dialogThemMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialogThemMoiLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(txtViTriCT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogThemMoiLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(txtGiaTriCT)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogThemMoiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogThemMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogThemMoiLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogThemMoiLayout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(175, 175, 175))))
        );
        dialogThemMoiLayout.setVerticalGroup(
            dialogThemMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogThemMoiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(dialogThemMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtViTriCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(dialogThemMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaTriCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnOK)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dialogXoa.setMinimumSize(new java.awt.Dimension(400, 250));

        btnOK1.setText("OK");
        btnOK1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        jLabel7.setText("XÓA MỘT PHẦN TỬ ");

        jLabel8.setText("Vị trí của phần tử cần xóa: ");

        txtViTriCX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViTriCXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogXoaLayout = new javax.swing.GroupLayout(dialogXoa.getContentPane());
        dialogXoa.getContentPane().setLayout(dialogXoaLayout);
        dialogXoaLayout.setHorizontalGroup(
            dialogXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogXoaLayout.createSequentialGroup()
                .addGroup(dialogXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogXoaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(dialogXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogXoaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34)
                                .addComponent(txtViTriCX, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)))
                    .addGroup(dialogXoaLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel7)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogXoaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOK1)
                .addGap(164, 164, 164))
        );
        dialogXoaLayout.setVerticalGroup(
            dialogXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogXoaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogXoaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8))
                    .addComponent(txtViTriCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btnOK1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        dialogKTx.setMinimumSize(new java.awt.Dimension(400, 250));

        btnOK2.setText("OK");
        btnOK2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK2ActionPerformed(evt);
            }
        });

        jLabel10.setText("KIỂM TRA PHẦN TỬ X");

        jLabel11.setText("Nhập phần tử cần tìm: ");

        txtPTCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogKTxLayout = new javax.swing.GroupLayout(dialogKTx.getContentPane());
        dialogKTx.getContentPane().setLayout(dialogKTxLayout);
        dialogKTxLayout.setHorizontalGroup(
            dialogKTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogKTxLayout.createSequentialGroup()
                .addGroup(dialogKTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogKTxLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(dialogKTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(dialogKTxLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(34, 34, 34)
                                .addGroup(dialogKTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOK2)
                                    .addComponent(txtPTCT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(dialogKTxLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel10)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        dialogKTxLayout.setVerticalGroup(
            dialogKTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogKTxLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogKTxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogKTxLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11))
                    .addComponent(txtPTCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnOK2)
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        thoatButton.setText("Thoát");
        thoatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("MẢNG N SỐ TỰ NHIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        BkLabel.setText("Nhập số tự nhiên N: ");

        resultLabel.setText("Kết quả: ");

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        jLabel2.setText("Lựa chọn của bạn: ");

        soTNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soTNTextFieldActionPerformed(evt);
            }
        });

        chooseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Các phần tử của mảng và tổng của chúng", "Các phần tử chẵn của mảng và tổng của chúng", "Các phần tử lẻ của mảng và tổng của chúng", "Các phần tử là số nguyên tố của mảng và tổng của chúng", "Thêm 1 phần tử mới vào mảng", "Xoá phần tử thứ k của mảng", "Nhập 1 số x, kiểm tra x có trong mảng không, nếu có thì trả về vị trí của x trong mảng" }));
        chooseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseComboBoxActionPerformed(evt);
            }
        });

        btnThucHien.setText("Thực hiện");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        xoaButton.setText("Xóa");
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhập mảng: ");

        nhapmangTextArea.setColumns(20);
        nhapmangTextArea.setRows(5);
        nhapmangTextArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nhapmangTextAreaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(nhapmangTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thoatButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BkLabel)
                            .addComponent(resultLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseComboBox, 0, 425, Short.MAX_VALUE)
                            .addComponent(soTNTextField)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BkLabel)
                    .addComponent(soTNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(chooseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoaButton)
                    .addComponent(btnThucHien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thoatButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int KT_Prime(int a){
        int count = 0;
        for(int i = 1; i <= a; i++){
            if(a % i == 0){
                 count++;
            }
        }
        if(count == 2){
            return 1;
        }
        return 0;
    }
    
    public String XoaKhoangTrangThua(String s){
        s = s.trim();
        s = s.replaceAll("\\s+"," ");
        return s;
    }
    
    private void thoatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_thoatButtonActionPerformed

    private void soTNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soTNTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soTNTextFieldActionPerformed

    private void chooseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseComboBoxActionPerformed
        // TODO add your handling code here:
        if(chooseComboBox.getSelectedIndex() == 4){
            dialogThemMoi.setVisible(true);
        }
        
        if(chooseComboBox.getSelectedIndex() == 5){
            dialogXoa.setVisible(true);
        }
        
        if(chooseComboBox.getSelectedIndex() == 6){
            dialogKTx.setVisible(true);
        }
    }//GEN-LAST:event_chooseComboBoxActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(soTNTextField.getText());
        String phanTu = nhapmangTextArea.getText();
        int choose = chooseComboBox.getSelectedIndex();
        int S = 0;
        resultTextArea.setText("");
        
        //Lấy phần tử mảng trong TextArea
            phanTu = XoaKhoangTrangThua(phanTu);          
            
            X = phanTu.split(" ");
        
        if(choose == 0){
            resultTextArea.append("Các phần tử của mảng là: ");
            for(int i = 0; i < n; i++){
                if(i < n - 1){
                    resultTextArea.append(X[i] + ", ");
                }
                else{
                    resultTextArea.append(X[i]);
                }
                S = S + Integer.parseInt(X[i]);
            }
            resultTextArea.append("\nTổng mảng: " + S);
        }

        if(choose == 1){
            resultTextArea.append("Các phần tử chẵn của mảng là: ");
            for(int i = 0; i < n; i++){
                if(Integer.parseInt(X[i]) % 2 == 0){
                    if(i < n - 2){
                        resultTextArea.append(X[i] + ", ");
                    }
                    else{
                        resultTextArea.append(X[i]);
                    }
                    S = S + Integer.parseInt(X[i]);
                }
            }
            resultTextArea.append("\nTổng các phần tử chẵn của mảng: " + S);
        }

        if(choose == 2){
            resultTextArea.append("Các phần tử lẻ của mảng là: ");
            for(int i = 0; i < n; i++){
                if(Integer.parseInt(X[i]) % 2 != 0){
                    if(i < n - 2){
                        resultTextArea.append(X[i] + ", ");
                    }
                    else{
                        resultTextArea.append(X[i]);
                    }
                    S = S + Integer.parseInt(X[i]);
                }
            }
            resultTextArea.append("\nTổng các phần tử lẻ của mảng: " + S);
        }

        if(choose == 3){
            resultTextArea.append("Các phần tử là số nguyên tố của mảng: ");
            for(int i = 0; i < n; i++){
                if(KT_Prime(Integer.parseInt(X[i])) == 1){
                    if(i < n){
                        resultTextArea.append(X[i] + ", ");
                    }
                    else{
                        resultTextArea.append(X[i]);
                    }
                    S = S + Integer.parseInt(X[i]);
                }
            }
            resultTextArea.append("\nTổng các phần tử là số nguyên tố của mảng: " + S);
        }

        if(choose == 4){
            int vt = Integer.parseInt(txtViTriCT.getText());
            String x = txtGiaTriCT.getText();            
            String Y[] = new String[1000];
            
            for(int i = 0; i < n; i++){
                Y[i] = X[i];
            }
            
            if(vt < 0){
                vt = 0;
            }
            
            else if(vt > n){
                vt = n;
            }
                                  
            for(int i = n; i > vt; i--){
                Y[i] = Y[i - 1];
            }
                        
            Y[vt] = x;
            ++n;
            
            for(int i = 0; i < n; i++){
               // resultTextArea.append(" i = " + i + " " + Y[i] + " \n");
                
                if(i < n - 1){
                    resultTextArea.append(Y[i] + ", ");
                }
                else{
                    resultTextArea.append(Y[i]);
                }
            }        
        }
        
        if(choose == 5){
            int k = Integer.parseInt(txtViTriCX.getText());
            if(k < 0){
                k = 0;
            }
            else if(k >= n){
                k = n-1;
            }
            for(int i = k; i < n - 1; i++){
                X[i] = X[i + 1];
            }
            n--;
            for(int i = 0; i < n; i++){
                if(i < n - 1){
                    resultTextArea.append(X[i] + ", ");
                }
                else{
                    resultTextArea.append(X[i]);
                }
            }
        }
        
        if(choose == 6){
            int check = 0;
            int x = Integer.parseInt(txtPTCT.getText());
            for(int i = 0; i < n; i++){
                if(Integer.parseInt(X[i]) == x){
                    resultTextArea.append(i + " ");
                    check = 1;
                }
            }
            if(check == 0) {
                resultTextArea.append("Không tồn tại phần tử x cần tìm!");
            }
        }
    }//GEN-LAST:event_btnThucHienActionPerformed

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaButtonActionPerformed
        // TODO add your handling code here:
        soTNTextField.setText("");
        resultLabel.setText("Kết quả: ");
        nhapmangTextArea.setText("");
        resultTextArea.setText("");
    }//GEN-LAST:event_xoaButtonActionPerformed

    private void nhapmangTextAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nhapmangTextAreaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapmangTextAreaAncestorAdded

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        dialogThemMoi.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtViTriCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViTriCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViTriCTActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        // TODO add your handling code here:
        dialogXoa.setVisible(false);

    }//GEN-LAST:event_btnOK1ActionPerformed

    private void txtViTriCXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViTriCXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViTriCXActionPerformed

    private void btnOK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK2ActionPerformed
        // TODO add your handling code here:
        dialogKTx.setVisible(false);
    }//GEN-LAST:event_btnOK2ActionPerformed

    private void txtPTCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTCTActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBT8_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBT8_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBT8_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBT8_C0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBT8_C0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BkLabel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnOK2;
    private javax.swing.JButton btnThucHien;
    private javax.swing.JComboBox<String> chooseComboBox;
    private javax.swing.JDialog dialogKTx;
    private javax.swing.JDialog dialogThemMoi;
    private javax.swing.JDialog dialogXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea nhapmangTextArea;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JTextField soTNTextField;
    private javax.swing.JButton thoatButton;
    private javax.swing.JTextField txtGiaTriCT;
    private javax.swing.JTextField txtPTCT;
    private javax.swing.JTextField txtViTriCT;
    private javax.swing.JTextField txtViTriCX;
    private javax.swing.JButton xoaButton;
    // End of variables declaration//GEN-END:variables
}
